server:
  port: 8080
spring:
  datasource:          #多数据源配置，默认数据源
    jdbc-url: jdbc:mysql://47.101.161.159:3306/zx
    username: root
    password: Xyqzlp..01190623
    driver-class-name: com.mysql.jdbc.Driver
  second-datasource:  #多数据源配置，第二数据源
    jdbc-url: jdbc:mysql://47.101.161.159:3306/zx
    username: root
    password: Xyqzlp..01190623
    driver-class-name: com.mysql.jdbc.Driver




